### ISSUE TITLE
Use v10.2.2 of CMP, remove server-side special cases

### ISSUE THREAD

**Issue by kenoir** [guardian/support-frontend#3535]
Following the merge of https://github.com/guardian/consent-management-platform/pull/559 and release of https://github.com/guardian/consent-management-platform/releases/tag/v10.2.2 you should no longer need to deal with the special case of server-side includes of the CMP code.

These cases can hopefully now be removed:

https://github.com/guardian/support-frontend/blob/832fd23498c4228d2dc63f7f8c3ecb95f4e831d5/support-frontend/assets/helpers/tracking/thirdPartyTrackingConsent.ts#L30

**Comment by kenoir** [comment]
Ping for this @GHaberis

**Comment by GHaberis** [comment]
@kenoir 👋  we have a prioritised health card for this to be added to our next Sprint (kicks off next week)
